---
title: "Models - BUILDING"
author: "David Gibert Bosque"
date: "December 14, 2018"
output: html_document
---
```{r include=FALSE}
rm(list = ls())
```

```{r include=FALSE}
### LIBRARIES ###
library(dplyr)
library(Metrics)
library(rpart)
library(doParallel)
library(rpart.plot)
library(fastDummies)
library(ggplot2)
library(elasticnet)
library(lars)
library(caret)
library(AppliedPredictiveModeling)
library(e1071)
library(pls)
library(plotly)
```

```{r include=FALSE}
## LOADING DATA
setwd("C:/Users/David/Google Drive/Github/task3-2-wifi-dgibert17")

load(file = "training.Rdata")
load(file = "validation.Rdata")

# cl <- makeCluster(3)
# doParallel:::registerDoParallel(cl)
```

#### PREDICCIONES SOBRE BULDING
## KNN para building
```{r}
building.vec = createDataPartition(y = df.train$BUILDINGID, p = 0.05)

# Training data
building.tr = df.train[building.vec$Resample1, c(1:last(grep(pattern = "WAP", names(df.train))), which(names(df.train) == "BUILDINGID"))]
building.tr$BUILDINGID = factor(building.tr$BUILDINGID)

# Test data
# VALIDATION DF

# Tabla de proporciones para ver que la proporcion de observaciones por BUILDING es la misma en el DF original que en el building.tr
prop.table(table(df.train$BF))
prop.table(table(building.tr$BF))

ctrl = trainControl(method = "repeatedcv",
                    number = 3,
                    repeats = 10)

knn.fit.building = train(BUILDINGID~.,
                method = "knn",
                trControl = ctrl,
                data = building.tr)
knn.fit.building

knn.pred.building = predict(knn.fit.building, df.val)
accuracy(actual = df.val$BUILDINGID, predicted = knn.pred.building)

#Cuantas observaciones hay predichas por edificio y cuantas hay en realidad en total.
table(knn.pred.building)
table(df.val$BUILDINGID)

#Cuantos dispositivos se han clasificado mal por cada edificio.
abs(table(knn.pred.building) - table(df.val$BUILDINGID))
```

## SVM para building
```{r warning=FALSE}
svmLin.fit.building <- train(BUILDINGID~.,
                    method = "svmLinear",
                    trControl = ctrl,
                    data = building.tr
                   )
svmLin.fit.building

svmLin.pred.building = predict(svmLin.fit.building, df.val)
accuracy(actual = df.val$BUILDINGID, predicted = svmLin.pred.building)


svmRad.fit.building <- train(BUILDINGID~.,
                    method = "svmRadial",
                    trControl = ctrl,
                    data = building.tr
                   )
svmRad.fit.building

svmRad.pred.building = predict(svmRad.fit.building, df.val)
accuracy(actual = df.val$BUILDINGID, predicted = svmRad.pred.building)


#Cuantas observaciones hay predichas por edificio y cuantas hay en realidad en total.
table(svmRad.pred.building)
table(df.val$BUILDINGID)

#Cuantos dispositivos se han clasificado mal por cada edificio.
abs(table(svmRad.pred.building) - table(df.val$BUILDINGID))
```

## RF para building
```{r}
rf.fit.building = train(BUILDINGID~.,
                  data = building.tr,
                  method = "rf",
                  ntree = 5,
                  trControl = ctrl,
                  allowParallel = TRUE
                  )

rf.pred.building = predict(rf.fit.building, df.val)
accuracy(actual = df.val$BUILDINGID, predicted = rf.pred.building)
```
